/**
 * Content script entry point.
 * Orchestrates subtitle translation and page element translation on YouTube pages.
 */
(function () {
  var state = {
    initialized: false,
    videoId: null,
    settings: {
      subtitle: true,
      comments: true,
      title: true,
      description: true,
      liveChat: true
    }
  };

  var subTranslator = new YTTranslate.Translator();

  /**
   * Load settings from chrome.storage and initialize.
   */
  function loadSettings() {
    return new Promise(function (resolve) {
      chrome.storage.local.get(['settings', 'apiKey'], function (result) {
        if (result.settings) {
          for (var key in result.settings) {
            state.settings[key] = result.settings[key];
          }
        }
        console.log('YT Translate: Settings loaded', JSON.stringify(state.settings), 'apiKey configured:', !!result.apiKey);
        resolve();
      });
    });
  }

  /**
   * Detect if current page is a YouTube watch page.
   */
  function isWatchPage() {
    return /^\/watch/.test(location.pathname);
  }

  /**
   * Extract video ID from URL.
   */
  function getVideoId() {
    var params = new URLSearchParams(location.search);
    return params.get('v') || null;
  }

  /**
   * Initialize subtitle translation system.
   */
  function initSubtitle() {
    console.log('YT Translate: initSubtitle called, subtitle enabled:', state.settings.subtitle);
    if (!state.settings.subtitle) return;

    var videoId = getVideoId();
    console.log('YT Translate: videoId =', videoId);
    if (!videoId) return;

    state.videoId = videoId;

    YTTranslate.extractor.extractSubtitles().then(function (result) {
      if (!result || result.subtitles.length === 0) {
        console.log('YT Translate: No subtitles available for this video');
        YTTranslate.overlay.init([], videoId);
        YTTranslate.overlay.showNoCaptions();
        return;
      }

      console.log(
        'YT Translate: Found ' + result.subtitles.length + ' subtitles [' +
        result.trackInfo.languageCode + ']' +
        (result.trackInfo.isAutoGenerated ? ' (auto)' : '')
      );

      YTTranslate.overlay.init(result.subtitles, videoId);

      var subtitles = result.subtitles;
      var texts = [];
      for (var i = 0; i < subtitles.length; i++) {
        texts.push(subtitles[i].text);
      }

      var BATCH_SIZE = 30;
      var batches = [];
      for (var b = 0; b < texts.length; b += BATCH_SIZE) {
        batches.push(texts.slice(b, b + BATCH_SIZE));
      }

      console.log('YT Translate: Translating in ' + batches.length + ' batches...');

      var allTranslations = [];
      var completed = 0;

      function processBatch(index) {
        if (index >= batches.length) {
          YTTranslate.overlay.setTranslations(allTranslations);
          console.log('YT Translate: All subtitles translated');
          return;
        }
        subTranslator.translateBatch(batches[index]).then(function (batchResult) {
          Array.prototype.push.apply(allTranslations, batchResult);
          completed++;
          console.log('YT Translate: Batch ' + completed + '/' + batches.length + ' done');
          processBatch(index + 1);
        }).catch(function (err) {
          console.warn('YT Translate: Batch ' + index + ' failed', err.message);
          for (var k = 0; k < batches[index].length; k++) {
            allTranslations.push('');
          }
          completed++;
          processBatch(index + 1);
        });
      }

      processBatch(0);

    }).catch(function (err) {
      console.warn('YT Translate: Subtitle extraction failed', err.message);
    });
  }

  /**
   * Initialize page element translation.
   */
  function initPageTranslation() {
    var pageSettings = {
      title: state.settings.title,
      description: state.settings.description,
      comments: state.settings.comments,
      liveChat: state.settings.liveChat
    };
    YTTranslate.observer.start(pageSettings);
    console.log('YT Translate: Page translation observer started');
  }

  /**
   * Full initialization: load settings, then init all systems.
   */
  function initialize() {
    console.log('YT Translate: initialize called, current state.initialized =', state.initialized);

    loadSettings().then(function () {
      console.log('YT Translate: location.pathname =', location.pathname, 'isWatchPage:', isWatchPage());
      if (!isWatchPage()) {
        console.log('YT Translate: Not a watch page, skipping subtitle init');
        return;
      }

      state.initialized = true;

      // Wait for video element to be ready
      var retries = 0;
      function tryInitSubtitle() {
        var video = document.querySelector('video');
        if (video && video.readyState >= 1) {
          console.log('YT Translate: Video element ready, starting subtitle init');
          initSubtitle();
        } else if (retries < 20) {
          retries++;
          setTimeout(tryInitSubtitle, 500);
        } else {
          console.log('YT Translate: Video element not found after retries, starting anyway');
          initSubtitle();
        }
      }
      setTimeout(tryInitSubtitle, 1000);

      // Initialize page translation on DOM ready
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initPageTranslation);
      } else {
        initPageTranslation();
      }
    });
  }

  /**
   * Teardown current state for SPA navigation.
   */
  function teardown() {
    YTTranslate.overlay.destroy();
    YTTranslate.observer.stop();
    state.initialized = false;
    state.videoId = null;
  }

  // --- Bootstrap ---

  console.log('YT Translate: Content script loaded, starting initialization');
  
  // Wait a bit for the page to settle, then initialize
  setTimeout(initialize, 500);

  // SPA navigation handling
  document.addEventListener('yt-navigate-finish', function () {
    console.log('YT Translate: SPA navigation detected');
    teardown();
    setTimeout(initialize, 500);
  });

  // Listen for settings updates from popup
  chrome.runtime.onMessage.addListener(function (request, sender, sendResponse) {
    if (request.type === 'SETTINGS_UPDATED') {
      console.log('YT Translate: Settings updated from popup, reinitializing');
      teardown();
      state.settings = request.settings;
      setTimeout(initialize, 300);
      sendResponse({ success: true });
    }
    if (request.type === 'GET_STATUS') {
      sendResponse({
        initialized: state.initialized,
        videoId: state.videoId,
        settings: state.settings
      });
    }
    // Handle force reinit from popup save action
    if (request.type === 'REINIT') {
      console.log('YT Translate: Forced reinit from popup');
      teardown();
      setTimeout(initialize, 300);
      sendResponse({ success: true });
    }
  });

})();
