/**
 * Content script entry point.
 * Orchestrates subtitle translation and page element translation on YouTube pages.
 */
(function () {
  var state = {
    initialized: false,
    videoId: null,
    settings: {
      subtitle: true,
      comments: true,
      title: true,
      description: true,
      liveChat: true
    }
  };

  var subTranslator = new YTTranslate.Translator();

  /**
   * Load settings from chrome.storage and initialize.
   */
  function loadSettings() {
    return new Promise(function (resolve) {
      chrome.storage.local.get(['settings', 'apiKey'], function (result) {
        if (result.settings) {
          for (var key in result.settings) {
            state.settings[key] = result.settings[key];
          }
        }
        resolve();
      });
    });
  }

  /**
   * Detect if current page is a YouTube watch page.
   */
  function isWatchPage() {
    return /^\/watch/.test(location.pathname);
  }

  /**
   * Detect if current page has live chat.
   */
  function isLivePage() {
    return !!document.querySelector('ytd-live-chat-frame');
  }

  /**
   * Extract video ID from URL.
   */
  function getVideoId() {
    var params = new URLSearchParams(location.search);
    return params.get('v') || null;
  }

  /**
   * Initialize subtitle translation system.
   */
  function initSubtitle() {
    if (!state.settings.subtitle) return;

    var videoId = getVideoId();
    if (!videoId) return;

    state.videoId = videoId;

    YTTranslate.extractor.extractSubtitles().then(function (result) {
      if (!result || result.subtitles.length === 0) {
        console.log('YT Translate: No subtitles available for this video');
        // Mount overlay anyway for "no captions" message
        YTTranslate.overlay.init([], videoId);
        YTTranslate.overlay.showNoCaptions();
        return;
      }

      console.log(
        'YT Translate: Found ' + result.subtitles.length + ' subtitles [' +
        result.trackInfo.languageCode + ']' +
        (result.trackInfo.isAutoGenerated ? ' (auto)' : '')
      );

      // Mount overlay with raw subtitles
      YTTranslate.overlay.init(result.subtitles, videoId);

      // Translate in batches of 30
      var subtitles = result.subtitles;
      var texts = [];
      for (var i = 0; i < subtitles.length; i++) {
        texts.push(subtitles[i].text);
      }

      var BATCH_SIZE = 30;
      var batches = [];
      for (var b = 0; b < texts.length; b += BATCH_SIZE) {
        batches.push(texts.slice(b, b + BATCH_SIZE));
      }

      console.log('YT Translate: Translating in ' + batches.length + ' batches...');

      var allTranslations = [];
      var completed = 0;

      function processBatch(index) {
        if (index >= batches.length) {
          YTTranslate.overlay.setTranslations(allTranslations);
          console.log('YT Translate: All subtitles translated');
          return;
        }
        subTranslator.translateBatch(batches[index]).then(function (batchResult) {
          Array.prototype.push.apply(allTranslations, batchResult);
          completed++;
          console.log('YT Translate: Batch ' + completed + '/' + batches.length + ' done');
          processBatch(index + 1);
        }).catch(function (err) {
          console.warn('YT Translate: Batch ' + index + ' failed', err.message);
          // Fill with empty strings and continue
          for (var k = 0; k < batches[index].length; k++) {
            allTranslations.push('');
          }
          completed++;
          processBatch(index + 1);
        });
      }

      processBatch(0);

    }).catch(function (err) {
      console.warn('YT Translate: Subtitle extraction failed', err.message);
    });
  }

  /**
   * Initialize page element translation.
   */
  function initPageTranslation() {
    var pageSettings = {
      title: state.settings.title,
      description: state.settings.description,
      comments: state.settings.comments,
      liveChat: state.settings.liveChat
    };
    YTTranslate.observer.start(pageSettings);
  }

  /**
   * Full initialization: load settings, then init all systems.
   */
  function initialize() {
    if (state.initialized) return;

    loadSettings().then(function () {
      if (!isWatchPage()) {
        // Non-watch page: only do page translation if appropriate
        return;
      }

      state.initialized = true;

      // Initialize subtitle system with a small delay to let page fully load
      setTimeout(initSubtitle, 800);

      // Initialize page translation on DOM ready
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initPageTranslation);
      } else {
        initPageTranslation();
      }
    });
  }

  /**
   * Teardown current state for SPA navigation.
   */
  function teardown() {
    YTTranslate.overlay.destroy();
    YTTranslate.observer.stop();
    state.initialized = false;
    state.videoId = null;
  }

  // --- Bootstrap ---

  // Initial page load
  initialize();

  // SPA navigation handling
  document.addEventListener('yt-navigate-finish', function () {
    teardown();
    // Small delay to let new page DOM settle
    setTimeout(initialize, 300);
  });

  // Listen for settings updates from popup
  chrome.runtime.onMessage.addListener(function (request, sender, sendResponse) {
    if (request.type === 'SETTINGS_UPDATED') {
      teardown();
      state.settings = request.settings;
      initialize();
      sendResponse({ success: true });
    }
    if (request.type === 'GET_STATUS') {
      sendResponse({
        initialized: state.initialized,
        videoId: state.videoId,
        settings: state.settings
      });
    }
  });

})();
