/**
 * Subtitle data extractor for YouTube.
 * Extracts caption track data from ytInitialPlayerResponse and fetches timed text.
 */
(function () {
  var extractor = {};

  /**
   * Get ytInitialPlayerResponse from the page.
   * Uses script injection to access the page''s JS context.
   */
  extractor.getPlayerResponse = function () {
    return new Promise(function (resolve) {
      var script = document.createElement('script');
      script.textContent =
        'window.postMessage({type:"YT_PLAYER_RESPONSE",data:window.ytInitialPlayerResponse},"*");';
      document.documentElement.appendChild(script);
      script.remove();

      function handler(event) {
        if (event.data && event.data.type === 'YT_PLAYER_RESPONSE') {
          window.removeEventListener('message', handler);
          resolve(event.data.data || null);
        }
      }
      window.addEventListener('message', handler);

      // Timeout fallback
      setTimeout(function () {
        window.removeEventListener('message', handler);
        resolve(null);
      }, 3000);
    });
  };

  /**
   * Extract caption tracks from player response.
   * @returns {{tracks: Array, selectedIndex: number}|null}
   */
  extractor.getCaptionTracks = function (playerResponse) {
    try {
      var tracks = playerResponse.captions
        .playerCaptionsTracklistRenderer
        .captionTracks;

      if (!tracks || tracks.length === 0) return null;

      // Prefer English track, then auto-generated English, then first available
      var selectedIndex = 0;
      for (var i = 0; i < tracks.length; i++) {
        if (tracks[i].languageCode === 'en' && tracks[i].kind !== 'asr') {
          selectedIndex = i;
          break;
        }
      }
      // Fallback to auto-generated English
      if (selectedIndex === 0) {
        for (var j = 0; j < tracks.length; j++) {
          if (tracks[j].languageCode === 'en') {
            selectedIndex = j;
            break;
          }
        }
      }

      return { tracks: tracks, selectedIndex: selectedIndex };
    } catch (e) {
      console.warn('YT Translate: Failed to extract caption tracks', e);
      return null;
    }
  };

  /**
   * Fetch and parse timed text from YouTube caption track URL.
   * @param {string} baseUrl - Caption track base URL
   * @returns {Promise<Array<{start: number, dur: number, text: string}>>}
   */
  extractor.fetchTimedText = function (baseUrl) {
    return fetch(baseUrl)
      .then(function (response) { return response.text(); })
      .then(function (xmlText) {
        var parser = new DOMParser();
        var doc = parser.parseFromString(xmlText, 'text/xml');
        var texts = doc.querySelectorAll('text');
        var subtitles = [];

        for (var i = 0; i < texts.length; i++) {
          var el = texts[i];
          var start = parseFloat(el.getAttribute('start') || '0');
          var dur = parseFloat(el.getAttribute('dur') || '0');
          var text = (el.textContent || '').trim();

          // Decode HTML entities
          var txt = document.createElement('textarea');
          txt.innerHTML = text;
          text = txt.value;

          if (text) {
            subtitles.push({ start: start, dur: dur, text: text });
          }
        }

        return subtitles;
      });
  };

  /**
   * Full extraction pipeline: get player response -> get tracks -> fetch timed text.
   * @returns {Promise<{subtitles: Array, trackInfo: object}|null>}
   */
  extractor.extractSubtitles = function () {
    var self = this;
    return this.getPlayerResponse().then(function (playerResponse) {
      if (!playerResponse) return null;

      var trackData = self.getCaptionTracks(playerResponse);
      if (!trackData) return null;

      var track = trackData.tracks[trackData.selectedIndex];
      return self.fetchTimedText(track.baseUrl).then(function (subtitles) {
        return {
          subtitles: subtitles,
          trackInfo: {
            languageCode: track.languageCode,
            name: track.name ? track.name.simpleText || track.languageCode : track.languageCode,
            isAutoGenerated: track.kind === 'asr'
          }
        };
      });
    });
  };

  YTTranslate.extractor = extractor;
})();
